### ISSUE TITLE
The app constantly crashes on Emulator in both Release and Debug mode, barely useable.

### ISSUE THREAD

**Issue by johnnynanjiang** [elastos/Elastos.App.Wallet.Elephant.Android#218]
The app crashes on PIN screen

E/WalletEthManager: getTokenBalance: App in background!
E/com.platform.APIClient: sendRequest: 
    java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:227)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at com.platform.APIClient.sendHttpRequest(APIClient.java:368)
        at com.platform.APIClient.sendRequest(APIClient.java:410)
        at com.breadwallet.tools.manager.BRApiManager.urlGET(BRApiManager.java:371)
        at com.breadwallet.tools.manager.BRApiManager.updateErc20Rates(BRApiManager.java:228)
        at com.breadwallet.tools.manager.BRApiManager.access$200(BRApiManager.java:71)
        at com.breadwallet.tools.manager.BRApiManager$2.run(BRApiManager.java:164)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.breadwallet.tools.threads.executor.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.SocketException: socket is closed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:551)
        at okio.Okio$2.read(Okio.java:138)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344) 
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216) 
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) 
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
        at okhttp3.RealCall.execute(RealCall.java:69) 
        at com.platform.APIClient.sendHttpRequest(APIClient.java:368) 
        at com.platform.APIClient.sendRequest(APIClient.java:410) 
        at com.breadwallet.tools.manager.BRApiManager.urlGET(BRApiManager.java:371) 
        at com.breadwallet.tools.manager.BRApiManager.updateErc20Rates(BRApiManager.java:228) 
        at com.breadwallet.tools.manager.BRApiManager.access$200(BRApiManager.java:71) 
        at com.breadwallet.tools.manager.BRApiManager$2.run(BRApiManager.java:164) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.breadwallet.tools.threads.executor.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47) 
        at java.lang.Thread.run(Thread.java:764) 
E/com.platform.APIClient: BRResponse: https://node1.elaphant.app/api/1/cmc?limit=1000 (599)|timeout|
E/com.breadwallet.tools.manager.BRApiManager: urlGET: strDate is null!
I/com.breadwallet.tools.manager.BRApiManager: updateErc20Rates result:timeout
E/com.breadwallet.tools.manager.BRReportsManager: reportBug: 
    org.json.JSONException: Value timeout of type java.lang.String cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONArray.<init>(JSONArray.java:96)
        at org.json.JSONArray.<init>(JSONArray.java:108)
        at com.breadwallet.tools.manager.BRApiManager.updateErc20Rates(BRApiManager.java:235)
        at com.breadwallet.tools.manager.BRApiManager.access$200(BRApiManager.java:71)
        at com.breadwallet.tools.manager.BRApiManager$2.run(BRApiManager.java:164)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.breadwallet.tools.threads.executor.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: org.json.JSONException: Value timeout of type java.lang.String cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONArray.<init>(JSONArray.java:96)
        at org.json.JSONArray.<init>(JSONArray.java:108)
        at com.breadwallet.tools.manager.BRApiManager.updateErc20Rates(BRApiManager.java:235)
        at com.breadwallet.tools.manager.BRApiManager.access$200(BRApiManager.java:71)
        at com.breadwallet.tools.manager.BRApiManager$2.run(BRApiManager.java:164)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.breadwallet.tools.threads.executor.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
I/bread: 2001:56b:dda9:4b00:49f9:121b:aa9e:de30:8333 adding block #1000, false positive rate: 0.000048

**Comment by xidaokun** [comment]
What is your Android simulator CPU architecture

**Comment by xidaokun** [comment]
What is your Android simulator CPU architecture？
